export const services = [
  {
    id: "outsourcing",
    title: "Specialized Outsourcing",
    subtitle: "Knowledge-intensive, not generic",
    description: "Specialized outsourcing delegates deep-expertise processes to external experts who do it better, faster, or more efficiently than building it in-house. Available at any stage of the data-to-deployment pipeline — from IT infrastructure to clinical trial management to computational chemistry. We source global specialists without the recruiting, retention, or benefits burden.",
    metrics: "6-week engagement, $500K+ saved vs. in-house build",
    features: ["Elite talent, zero ramp-up", "Fixed cost → variable operating expense", "Domain risk shared with specialist partner", "Scale up or down without headcount complexity"],
    icon: "Users",
  },
  {
    id: "skill-hiring",
    title: "Specialized Skill Hiring",
    subtitle: "Fractional experts on-demand, defined scope",
    description: "Need a principal Rust compiler developer, a smart contract security auditor, or an ML operations expert for a critical project slice? We source and deploy elite specialists for high-impact milestones — deployed against a defined scope, quality bar, and timeline, not an open-ended headcount request. Domain risk is shared with a partner who lives in that domain daily.",
    metrics: "5–50 day engagements",
    features: ["Vetted deep specialty indexing", "Fractional or full-time engagement", "Immediate project onboarding", "Partner carries domain risk"],
    icon: "Briefcase",
  },
  {
    id: "ai-solutions",
    title: "AI Solutions & Automation",
    subtitle: "Seven components working in concert",
    description: "A true AI solution isn't an impressive model — it's seven components working in concert: problem framing, data strategy, model development, system integration, deployment, change management, and monitoring. We engineer all seven, not just the algorithm. Human-in-the-loop by design ensures planners and operators retain oversight — AI handles routine work, humans focus on exceptions.",
    metrics: "2–6 week MVP · 680% ROI at 36 months",
    features: ["Problem framing tied to measurable KPIs", "SHAP-based explainability for stakeholder trust", "Ensemble models over single-model bias", "Drift monitoring and retraining built in"],
    icon: "BrainCircuit",
  },
  {
    id: "data-annotations",
    title: "Data Annotation & Labeling",
    subtitle: "Consensus-verified, eight-dimension quality",
    description: "Annotation gives raw data meaning; labeling operationalizes it at scale; quality assurance is the gate that decides whether it's trustworthy enough to train on. We run all three as one continuous, auditable pipeline — with inter-annotator agreement (Cohen's Kappa) tracked and reported, not assumed.",
    metrics: "0.94 entity-level F1 · 99.98% consensus confidence",
    features: ["Ontology + guidelines before labeling starts", "Model-assisted pre-labeling, expert-reviewed", "Inter-annotator Kappa >0.91 achieved", "Eight-dimension quality scoring: accuracy, completeness, consistency, timeliness"],
    icon: "Layers",
  },
];
